## Process CSVs and prepare for Analysis and Machine Learning

In [2]:
# import libraries 
import pandas as pd 
import os

In [3]:
# create function to append all csv files together 
def concat_csv(file_path):
    '''function to concat all csv files into one
    parameters: file path for folder you want to concatenate
    return: combined_df(df)
    '''
    combined_df = pd.concat(
        [pd.read_csv(os.path.join(file_path, f), encoding='ISO-8859-1').assign(Tag=f)
         for f in os.listdir(file_path) if f.endswith('.csv')],
        ignore_index=True
    )
    return combined_df

### Preparing data for Ball Milling Data

In [5]:
# concatenate files and then initalize runtimes as None
concatenated_df  = concat_csv('/Users/sarah/Documents/Roux co-op/material recycling project/PyImageJ-Particle-Analysis/Ball Milling Powder Samples/Ball Milling Powder Sample CSV')
concatenated_df[['Ball-Powder Ratio', 'Jar', '20mm Run Time (Hours)', '10mm Run Time (Hours)','6mm Run Time (Hours)','Total Run Time (Hours)']] = None
concatenated_df.columns

Index([' ', 'Area', 'Mean', 'StdDev', 'Min', 'Max', 'X', 'Y', 'Perim.', 'BX',
       'BY', 'Width', 'Height', 'Major', 'Minor', 'Angle', 'Circ.', 'Feret',
       'IntDen', 'Median', 'Skew', 'Kurt', '%Area', 'RawIntDen', 'Slice',
       'FeretX', 'FeretY', 'FeretAngle', 'MinFeret', 'AR', 'Round', 'Solidity',
       'Tag', 'Ball-Powder Ratio', 'Jar', '20mm Run Time (Hours)',
       '10mm Run Time (Hours)', '6mm Run Time (Hours)',
       'Total Run Time (Hours)'],
      dtype='object')

In [ ]:
def update_features(concatenated_df, file_name, tag, bwratio, twenty_mm, ten_mm, six_mm, total, jar=None):
    '''update values in df to include feature values and update tag names'''
    concatenated_df['Tag'] = concatenated_df['Tag'].replace(file_name, tag)
    
    concatenated_df.loc[concatenated_df['Tag'] == tag, 'Ball-Powder Ratio'] = bwratio
    concatenated_df.loc[concatenated_df['Tag'] == tag, 'Jar'] = jar
    concatenated_df.loc[concatenated_df['Tag'] == tag, '20mm Run Time (Hours)'] = twenty_mm
    concatenated_df.loc[concatenated_df['Tag'] == tag, '10mm Run Time (Hours)'] = ten_mm
    concatenated_df.loc[concatenated_df['Tag'] == tag, '6mm Run Time (Hours)'] = six_mm
    concatenated_df.loc[concatenated_df['Tag'] == tag, 'Total Run Time (Hours)'] = total

    return concatenated_df

In [ ]:
# update based on data from milling excel 
concatenated_df = update_features(concatenated_df, file_name='Sample A.csv', tag='C1-20', bwratio='7:5:1', twenty_mm=20.0,ten_mm=0.0,six_mm=0.0, total=20.0, jar=1)
concatenated_df = update_features(concatenated_df, file_name='Sample B.csv', tag='C2-20', bwratio='7:5:1', twenty_mm=20.0,ten_mm=0.0,six_mm=0.0, total=20.0, jar=2)
concatenated_df = update_features(concatenated_df, file_name='Sample C.csv', tag='A6', bwratio='15:1', twenty_mm=32.0,ten_mm=16.0,six_mm=0.0, total=48.0)
concatenated_df = update_features(concatenated_df, file_name='Sample D.csv', tag='A5', bwratio='15:1', twenty_mm=32.0,ten_mm=8.0,six_mm=0.0, total=40.0)
concatenated_df = update_features(concatenated_df, file_name='Sample E.csv', tag='A4', bwratio='15:1', twenty_mm=32.0,ten_mm=0.0,six_mm=0.0, total=32.0)
concatenated_df = update_features(concatenated_df, file_name='Sample F.csv', tag='A3', bwratio='15:1', twenty_mm=23.7,ten_mm=0.0,six_mm=0.0, total=23.7)
concatenated_df = update_features(concatenated_df, file_name='Sample G.csv', tag='E1-10', bwratio='7:5:1', twenty_mm=20.0,ten_mm=16.7,six_mm=0.0, total=36.7, jar=1)
concatenated_df = update_features(concatenated_df, file_name='Sample G1-6.csv', tag='G1-6', bwratio='7:5:1', twenty_mm=20.0,ten_mm=25.0,six_mm=8.3, total=53.3, jar=1)
concatenated_df = update_features(concatenated_df, file_name='Sample G2-6.csv', tag='G2-6', bwratio='7:5:1', twenty_mm=20.0,ten_mm=25.0,six_mm=8.3, total=53.3, jar=2)
concatenated_df = update_features(concatenated_df, file_name='Sample H.csv', tag='E2-10', bwratio='7:5:1', twenty_mm=20.0,ten_mm=16.7,six_mm=0.0, total=36.7, jar=2)
concatenated_df = update_features(concatenated_df, file_name='Sample H1.csv', tag='H1-6', bwratio='7:5:1', twenty_mm=20.0,ten_mm=25.0,six_mm=16.7, total=61.7, jar=1)
concatenated_df = update_features(concatenated_df, file_name='Sample H2.csv', tag='H2-6', bwratio='7:5:1', twenty_mm=20.0,ten_mm=25.0,six_mm=16.7, total=61.7, jar=2)
concatenated_df = update_features(concatenated_df, file_name='Sample I.csv', tag='D1-10', bwratio='7:5:1', twenty_mm=20.0,ten_mm=8.3,six_mm=0, total=28.3, jar=1)
concatenated_df = update_features(concatenated_df, file_name='Sample 3 k2-6.csv', tag='K2-6', bwratio='7:5:1', twenty_mm=20.0,ten_mm=0.0,six_mm=16.7, total=36.7, jar=2)
concatenated_df = update_features(concatenated_df, file_name='Sample 3-M1-6.csv', tag='M1-6', bwratio='7:5:1', twenty_mm=20.0,ten_mm=0.0,six_mm=41.7, total=61.7, jar=1)
concatenated_df = update_features(concatenated_df, file_name='Sample 3-M2-6.csv', tag='M2-6', bwratio='7:5:1', twenty_mm=20.0,ten_mm=0.0,six_mm=41.7, total=61.7, jar=2)
concatenated_df = update_features(concatenated_df, file_name='Sample F1-10.csv', tag='F1-10', bwratio='7:5:1', twenty_mm=20.0,ten_mm=25.0,six_mm=0.0, total=45.0, jar=1)
concatenated_df = update_features(concatenated_df, file_name='Sample F2-10.csv', tag='F2-10', bwratio='7:5:1', twenty_mm=20.0,ten_mm=25.0,six_mm=0.0, total=45.0, jar=2)
concatenated_df = update_features(concatenated_df, file_name='Sample J1-20.csv', tag='J1-20', bwratio='7:5:1', twenty_mm=20.0,ten_mm=0.0,six_mm=0.0, total=20.0, jar=1)
concatenated_df = update_features(concatenated_df, file_name='Sample J2-20.csv', tag='J2-20', bwratio='7:5:1', twenty_mm=20.0,ten_mm=0.0,six_mm=0.0, total=20.0, jar=2)
concatenated_df = update_features(concatenated_df, file_name='Sample 4-O1.csv', tag='4-O1', bwratio='7:5:1', twenty_mm=0.0,ten_mm=0.0,six_mm=61.7, total=61.7, jar=1)
concatenated_df = update_features(concatenated_df, file_name='Sample 4-P1.csv', tag='4-P1', bwratio='7:5:1', twenty_mm=0.0,ten_mm=0.0,six_mm=61.7, total=61.7, jar=1)
concatenated_df = update_features(concatenated_df, file_name='Sample 4-P2.csv', tag='4-P2', bwratio='7:5:1', twenty_mm=0.0,ten_mm=0.0,six_mm=61.7, total=61.7, jar=2)
concatenated_df = update_features(concatenated_df, file_name='Sample 4-Q1-10.csv', tag='4-Q1-10', bwratio='7:5:1', twenty_mm=0.0,ten_mm=61.7,six_mm=0.0, total=61.7, jar=1)
concatenated_df = update_features(concatenated_df, file_name='Sample 4-Q2-10.csv', tag='4-Q2-10', bwratio='7:5:1', twenty_mm=0.0,ten_mm=61.7,six_mm=0.0, total=61.7, jar=2)
concatenated_df

In [ ]:
# reorder df 
concatenated_df = concatenated_df.drop(concatenated_df.columns[0],axis=1)
concatenated_df = concatenated_df[['Tag', 'Ball-Powder Ratio', 'Jar', '20mm Run Time (Hours)', '10mm Run Time (Hours)','6mm Run Time (Hours)','Total Run Time (Hours)', 'Circ.', 'Feret', 'AR', 'Round','Area', 'Mean', 'Perim.','BX','BY','Width','Height','Major','Minor','Angle','IntDen','RawIntDen','FeretX','FeretY','FeretAngle','MinFeret','Solidity','Skew','Slice','Kurt','Median','%Area','StdDev','Min','Max','X','Y']]
concatenated_df

In [ ]:
# save to csv
concatenated_df.to_csv('/Users/sarah/Documents/Roux co-op/material recycling project/PyImageJ-Particle-Analysis/Ball Milling Powder Samples/BallMilling ML Data.csv')

### Prepare Data for Reuse Powders

In [6]:
reuse_powder_data = concat_csv('/Users/sarah/Documents/Roux co-op/material recycling project/PyImageJ-Particle-Analysis/ALM Ortho Microscopy Powders/ALM Ortho Powders CSV')
reuse_powder_data

,,Area,Mean,StdDev,Min,Max,X,Y,Perim.,BX,...,RawIntDen,Slice,FeretX,FeretY,FeretAngle,MinFeret,AR,Round,Solidity,Tag
0,1,2764,255,0,255,255,264.488,52.241,206.836,235,...,704820,1,251,24,119.859,58.690,1.046,0.956,0.969,P2002 Rev 1 Group 6.csv
1,2,2554,255,0,255,255,697.684,146.339,198.593,669,...,651270,1,690,175,74.320,57.000,1.018,0.982,0.968,P2002 Rev 1 Group 6.csv
2,3,4042,255,0,255,255,1174.881,202.358,252.534,1139,...,1030710,1,1143,222,34.743,71.834,1.030,0.971,0.972,P2002 Rev 1 Group 6.csv
3,4,3943,255,0,255,255,474.880,222.687,240.250,438,...,1005465,1,438,209,163.009,70.441,1.039,0.963,0.968,P2002 Rev 1 Group 6.csv
4,5,943,255,0,255,255,421.992,220.350,117.640,405,...,240465,1,409,208,138.240,32.000,1.100,0.909,0.963,P2002 Rev 1 Group 6.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73415,145,2067,255,0,255,255,204.502,875.316,179.823,180,...,527085,1,184,900,54.689,50.688,1.100,0.909,0.948,P2316.csv
73416,146,2107,255,0,255,255,508.282,880.446,178.551,482,...,537285,1,486,866,148.671,52.000,1.002,0.998,0.964,P2316.csv
73417,147,3072,255,0,255,255,882.481,887.256,228.794,849,...,783360,1,850,869,157.496,54.059,1.338,0.748,0.923,P2316.csv
73418,148,1294,255,0,255,255,27.978,879.234,136.125,7,...,329970,1,11,893,34.046,39.000,1.079,0.927,0.962,P2316.csv
73419,149,1459,255,0,255,255,311.336,896.560,149.924,288,...,372045,1,296,913,49.268,43.000,1.023,0.978,0.949,P2316.csv

In [8]:
# add new columms for Lot, Rev, GroupID
reuse_powder_data['Lot'] = reuse_powder_data['Tag'].str.extract(r'([A-Z]\d+)')[0]
reuse_powder_data['Rev'] = reuse_powder_data['Tag'].str.extract(r'Rev (\d+)')[0]  
reuse_powder_data['GroupID'] = reuse_powder_data['Tag'].str.extract(r'Group (\d+)')[0]
reuse_powder_data

,,Area,Mean,StdDev,Min,Max,X,Y,Perim.,BX,...,FeretY,FeretAngle,MinFeret,AR,Round,Solidity,Tag,Lot,Rev,GroupID
0,1,2764,255,0,255,255,264.488,52.241,206.836,235,...,24,119.859,58.690,1.046,0.956,0.969,P2002 Rev 1 Group 6.csv,P2002,1,6
1,2,2554,255,0,255,255,697.684,146.339,198.593,669,...,175,74.320,57.000,1.018,0.982,0.968,P2002 Rev 1 Group 6.csv,P2002,1,6
2,3,4042,255,0,255,255,1174.881,202.358,252.534,1139,...,222,34.743,71.834,1.030,0.971,0.972,P2002 Rev 1 Group 6.csv,P2002,1,6
3,4,3943,255,0,255,255,474.880,222.687,240.250,438,...,209,163.009,70.441,1.039,0.963,0.968,P2002 Rev 1 Group 6.csv,P2002,1,6
4,5,943,255,0,255,255,421.992,220.350,117.640,405,...,208,138.240,32.000,1.100,0.909,0.963,P2002 Rev 1 Group 6.csv,P2002,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73415,145,2067,255,0,255,255,204.502,875.316,179.823,180,...,900,54.689,50.688,1.100,0.909,0.948,P2316.csv,P2316,NaN,NaN
73416,146,2107,255,0,255,255,508.282,880.446,178.551,482,...,866,148.671,52.000,1.002,0.998,0.964,P2316.csv,P2316,NaN,NaN
73417,147,3072,255,0,255,255,882.481,887.256,228.794,849,...,869,157.496,54.059,1.338,0.748,0.923,P2316.csv,P2316,NaN,NaN
73418,148,1294,255,0,255,255,27.978,879.234,136.125,7,...,893,34.046,39.000,1.079,0.927,0.962,P2316.csv,P2316,NaN,NaN
73419,149,1459,255,0,255,255,311.336,896.560,149.924,288,...,913,49.268,43.000,1.023,0.978,0.949,P2316.csv,P2316,NaN,NaN

In [ ]:
# read elemental data 
elemental_data = pd.read_csv('/Users/sarah/Documents/areospace research/material recycling project/Ti64_Composition_Tools/Ti_Powder_All_Lots/Powder Results Summary/Merged_Element_Composition_Tables.csv')
elemental_data

,Lot,GroupID,Rev,Aluminum (wt%),Carbon (wt%),Chromium (wt%),Hydrogen (wt%),Iron (wt%),Nickel (wt%),Nitrogen (wt%),Oxygen (wt%),Silicon (wt%),Titanium (wt%),Vanadium (wt%),Yttrium (wt%)
0,P1442,2,5,6.41,0.007,0.012,0.0018,0.19,0.010,0.010,0.158,0.010,89.2607,3.95,0.0005
1,P1442,3,3,6.51,0.010,0.014,0.0015,0.20,0.011,0.008,0.148,0.014,89.1380,3.97,0.0005
2,P1442,4,3,6.44,0.010,0.015,0.0017,0.24,0.011,0.005,0.142,0.013,89.2158,3.93,0.0005
3,P1442,5,1,6.50,0.011,0.013,0.0013,0.17,0.010,0.011,0.149,0.013,89.1142,4.03,0.0005
4,P1442,6,1,6.48,0.008,0.013,0.0012,0.19,0.010,0.014,0.162,0.013,89.0613,4.07,0.0005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,P1440,5,2,6.45,0.009,0.013,0.0011,0.20,0.011,0.019,0.158,0.013,89.2294,3.92,0.0005
138,P1440,3,5,6.37,0.007,0.011,0.0020,0.19,0.010,0.005,0.174,0.011,89.3505,3.89,0.0005
139,P1440,3,4,6.42,0.008,0.013,0.0019,3.91,0.010,0.012,0.188,0.010,89.2666,0.18,0.0005
140,P1440,5,3,6.36,0.008,0.013,0.0013,0.17,0.010,0.011,0.169,0.010,89.3272,3.94,0.0005
141,P1440,4,5,6.41,0.006,0.000,0.0014,4.00,0.000,0.013,0.181,0.012,89.1986,0.19,0.0005

In [ ]:
# convert columns to be same data type to be joined on
reuse_powder_data['Lot'] = reuse_powder_data['Lot'].astype(str)
reuse_powder_data['GroupID'] = reuse_powder_data['GroupID'].astype(str)
reuse_powder_data['Rev'] = reuse_powder_data['Rev'].astype(str)

elemental_data['Lot'] = elemental_data['Lot'].astype(str)
elemental_data['GroupID'] = elemental_data['GroupID'].astype(str)
elemental_data['Rev'] = elemental_data['Rev'].astype(str)

In [ ]:
# join dataframes on lot, groupid, rev and save to csv
merged_df = pd.merge(reuse_powder_data, elemental_data, on=['Lot', 'GroupID', 'Rev'], how='inner')
merged_df.to_csv('/Users/sarah/Documents/areospace research/material recycling project/PyImageJ-Particle-Analysis/ALM Ortho Powders/ALM_Ortho_Lots_and_elementdata.csv')
merged_df

,Name,Area (ABD) (µm²),Area (Filled) (µm²),Aspect Ratio,Average Blue,Average Green,Average Red,Biovolume (Cylinder) (µm³),Biovolume (P. Spheroid) (µm³),Biovolume (Sphere) (µm³),...,Chromium (wt%),Hydrogen (wt%),Iron (wt%),Nickel (wt%),Nitrogen (wt%),Oxygen (wt%),Silicon (wt%),Titanium (wt%),Vanadium (wt%),Yttrium (wt%)
0,2024-10-29 P1444 Group 2 Rev 9 R01 PP1,2594.22,2594.22,0.98,0.0,0.0,0.0,131035.95,98560.73,99397.30,...,0.017,0.0015,0.2,0.011,0.006,0.156,0.014,89.1320,4.00,0.0005
1,2024-10-29 P1444 Group 2 Rev 9 R01 PP1,2941.80,2941.80,0.88,0.0,0.0,0.0,149907.50,111999.03,120028.45,...,0.017,0.0015,0.2,0.011,0.006,0.156,0.014,89.1320,4.00,0.0005
2,2024-10-29 P1444 Group 2 Rev 9 R01 PP1,4747.18,4747.18,0.98,0.0,0.0,0.0,280546.24,243604.63,246046.63,...,0.017,0.0015,0.2,0.011,0.006,0.156,0.014,89.1320,4.00,0.0005
3,2024-10-29 P1444 Group 2 Rev 9 R01 PP1,3793.81,3793.81,0.97,0.0,0.0,0.0,194122.23,173024.12,175782.98,...,0.017,0.0015,0.2,0.011,0.006,0.156,0.014,89.1320,4.00,0.0005
4,2024-10-29 P1444 Group 2 Rev 9 R01 PP1,3345.44,3345.44,0.94,0.0,0.0,0.0,176646.79,140861.30,145560.42,...,0.017,0.0015,0.2,0.011,0.006,0.156,0.014,89.1320,4.00,0.0005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27448,2024-10-29 P1444 Group 1 Rev 9 R01_PP2,1006.28,1030.85,0.60,0.0,0.0,0.0,13393.78,39620.58,24012.83,...,0.015,0.0012,0.2,0.011,0.005,0.176,0.012,89.1103,4.07,0.0005
27449,2024-10-29 P1444 Group 1 Rev 9 R01_PP2,1690.90,1690.90,0.99,0.0,0.0,0.0,70625.15,52313.92,52304.47,...,0.015,0.0012,0.2,0.011,0.005,0.176,0.012,89.1103,4.07,0.0005
27450,2024-10-29 P1444 Group 1 Rev 9 R01_PP2,1885.41,1885.41,0.97,0.0,0.0,0.0,78279.69,60625.90,61584.50,...,0.015,0.0012,0.2,0.011,0.005,0.176,0.012,89.1103,4.07,0.0005
27451,2024-10-29 P1444 Group 1 Rev 9 R01_PP2,2439.02,2439.02,0.93,0.0,0.0,0.0,124922.67,87156.88,90612.29,...,0.015,0.0012,0.2,0.011,0.005,0.176,0.012,89.1103,4.07,0.0005
27452,2024-10-29 P1444 Group 1 Rev 9 R01_PP2,2075.60,2075.60,0.96,0.0,0.0,0.0,93669.15,69665.52,71134.10,...,0.015,0.0012,0.2,0.011,0.005,0.176,0.012,89.1103,4.07,0.0005